#### General guidance

This serves as a template which will guide you through the implementation of this task. It is advised
to first read the whole template and get a sense of the overall structure of the code before trying to fill in any of the TODO gaps.
This is the jupyter notebook version of the template. For the python file version, please refer to the file `template_solution.py`.

First, we import necessary libraries:

In [1]:
import numpy as np
import pandas as pd

# Add any additional imports here (however, the task is solvable without using 
# any additional imports)
# import ...

 #### Loading data

In [2]:
data = pd.read_csv("../train.csv")
y = data["y"].to_numpy()
data = data.drop(columns=["Id", "y"])
# print a few data samples
print(data.head())
X = data.to_numpy()

     x1    x2    x3    x4    x5
0  0.02  0.05 -0.09 -0.43 -0.08
1 -0.13  0.11 -0.08 -0.29 -0.03
2  0.08  0.06 -0.07 -0.41 -0.03
3  0.02 -0.12  0.01 -0.43 -0.02
4 -0.14 -0.12 -0.08 -0.02 -0.08


In [3]:
data.describe()

,x1,x2,x3,x4,x5
count,700.000000,700.000000,700.000000,700.000000,700.000000
mean,-0.057814,-0.054686,-0.059786,-0.281814,-0.055900
std,0.138694,0.120136,0.083381,0.150631,0.052697
min,-0.450000,-0.420000,-0.350000,-0.520000,-0.560000
25%,-0.150000,-0.140000,-0.110000,-0.390000,-0.080000
50%,-0.070000,-0.060000,-0.050000,-0.330000,-0.050000
75%,0.020000,0.020000,-0.010000,-0.200000,-0.030000
max,0.380000,0.360000,0.190000,0.440000,0.070000


#### Transform features

In [4]:
"""
Transform the 5 input features of matrix X (x_i denoting the i-th component of a given row in X) 
into 21 new features phi(X) in the following manner:
5 linear features: phi_1(X) = x_1, phi_2(X) = x_2, phi_3(X) = x_3, phi_4(X) = x_4, phi_5(X) = x_5
5 quadratic features: phi_6(X) = x_1^2, phi_7(X) = x_2^2, phi_8(X) = x_3^2, phi_9(X) = x_4^2, phi_10(X) = x_5^2
5 exponential features: phi_11(X) = exp(x_1), phi_12(X) = exp(x_2), phi_13(X) = exp(x_3), phi_14(X) = exp(x_4), phi_15(X) = exp(x_5)
5 cosine features: phi_16(X) = cos(x_1), phi_17(X) = cos(x_2), phi_18(X) = cos(x_3), phi_19(X) = cos(x_4), phi_20(X) = cos(x_5)
1 constant feature: phi_21(X)=1

Parameters
----------
X: matrix of floats, dim = (700,5), inputs with 5 features

Compute
----------
X_transformed: matrix of floats: dim = (700,21), transformed input with 21 features
"""
X_transformed = np.zeros((700, 21))
# TODO: Enter your code here

for i in range(5):
    X_transformed[:,i] = X[:,i]
for i in range(5,10):
    X_transformed[:,i] = (X[:,i-5])**2
for i in range(10,15):
    X_transformed[:,i] = np.exp(X[:,i-10])
for i in range(15,20):
    X_transformed[:,i] = np.cos(X[:,i-15])

X_transformed[:,20] = 1



assert X_transformed.shape == (700, 21)

In [ ]:
"""
Alternative faster way proposed here:
"""

# 5 linear features
X_transformed[:, 0:5] = X

# 5 quadratic features
X_transformed[:, 5:10] = X**2

# 5 exponential features
X_transformed[:, 10:15] = np.exp(X)

# 5 cosine features
X_transformed[:, 15:20] = np.cos(X)

# 1 constant feature
X_transformed[:, 20] = 1

assert X_transformed.shape == (700, 21)

In [6]:
X_transformed

array([[ 0.02      ,  0.05      , -0.09      , ...,  0.90896575,
         0.99680171,  1.        ],
       [-0.13      ,  0.11      , -0.08      , ...,  0.95824388,
         0.99955003,  1.        ],
       [ 0.08      ,  0.06      , -0.07      , ...,  0.91712082,
         0.99955003,  1.        ],
       ...,
       [-0.27      , -0.22      , -0.01      , ...,  0.94923542,
         0.99875026,  1.        ],
       [ 0.19      ,  0.11      , -0.05      , ...,  0.9637709 ,
         0.99920011,  1.        ],
       [-0.09      , -0.09      , -0.06      , ...,  0.91712082,
         0.99820054,  1.        ]], shape=(700, 21))

#### Fit data

In [7]:
"""
Use the transformed data points X_transformed and fit the logistic regression on this 
transformed data. Finally, compute the weights of the fitted logistic regression. 

Parameters
----------
X_transformed: array of floats: dim = (700,21), transformed input with 21 features
y: array of integers \in {0,1}, dim = (700,), input labels

Compute
----------
w: array of floats: dim = (21,), optimal parameters of logistic regression

METHOD 1: with sci-kit learn Logistic Regression built in class
"""

weights_scikit = np.zeros((21,))
# TODO: Enter your code here

from sklearn.linear_model import LogisticRegression

# the last feature, phi21 is 1, which is equivalent to fitting an intercept, so it is set to false
LogReg_fit = LogisticRegression(fit_intercept=False).fit(X_transformed,y)

print(LogReg_fit.coef_[0])

weights_scikit = LogReg_fit.coef_[0]

assert weights_scikit.shape == (21,)

[-0.64714014 -4.604063    3.70712977 -0.60552636 -4.81916544  0.33526013
  1.50757875 -0.42884808 -0.50684443  0.71943419  0.04210832 -3.35493966
  4.03668746 -0.3031044  -3.95057527  0.36253373 -0.22109721  0.74247043
  0.77647758  0.17022714  0.5288481 ]


In [8]:
# Save results in the required format
np.savetxt("./task1b_results_scikit_cr.csv", weights_scikit, fmt="%.12f")

In [ ]:
"""
Use the transformed data points X_transformed and fit the logistic regression on this 
transformed data. Finally, compute the weights of the fitted logistic regression. 

Parameters
----------
X_transformed: array of floats: dim = (700,21), transformed input with 21 features
y: array of integers \in {0,1}, dim = (700,), input labels

Compute
----------
w: array of floats: dim = (21,), optimal parameters of logistic regression

METHOD 2: manually with the Numpy package
"""
weights_manual = np.zeros((21,))
# TODO: Enter your code here

# defining the Sigmoid activation function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# setting the Gradient Descent hyperparameters
learning_rate = 0.1     # Also known as alpha, controls step size
num_iterations = 10000  # Number of times we update the weights
m = X_transformed.shape[0] # Number of training examples (700)

# gradient Descent Optimization Loop
for i in range(num_iterations):
    # Step A: Calculate the current predictions
    # h = sigmoid(X * weights)
    linear_predictions = np.dot(X_transformed, weights_manual)
    predictions = sigmoid(linear_predictions)
    
    # Step B: Calculate the gradient (how far off we are, scaled by X)
    # The derivative of the log-loss cost function simplifies beautifully to this:
    gradient = np.dot(X_transformed.T, (predictions - y)) / m
    
    # Step C: Update the weights by taking a step in the opposite direction of the gradient
    weights_manual -= learning_rate * gradient

assert weights_manual.shape == (21,)

In [10]:
weights_manual

array([-0.48924568, -6.80571768,  5.78619876, -0.76221753, -7.61140242,
        0.42276086,  2.19762962, -0.70001271, -0.81599427,  1.17198307,
        0.47822251, -4.99421302,  6.2246866 , -0.3630973 , -6.29640892,
        0.55402038, -0.32949261,  1.11227954,  1.16258182,  0.17980172,
        0.76362502])

In [11]:
# Save results in the required format
np.savetxt("./task1b_results_manual_cr.csv", weights_manual, fmt="%.12f")

In [ ]:
# there seems to be a difference in the weights obtained by the two methods
abs(weights_scikit-weights_manual)

array([0.15789446, 2.20165468, 2.07906899, 0.15669117, 2.79223698,
       0.08750073, 0.69005087, 0.27116462, 0.30914984, 0.45254888,
       0.43611419, 1.63927336, 2.18799914, 0.05999291, 2.34583365,
       0.19148665, 0.10839541, 0.3698091 , 0.38610424, 0.00957458,
       0.23477693])